import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { SERVICE_MODES, splitMode, type ServiceMode } from "@/lib/serviceMode";

export interface ModeSession {
  id: string; user_id: string; plan_id: string;
  session_date: string; time_slot: string | null;
  status: string; attended: boolean | null;
  society_id: string | null; batch_id: string | null;
  service_mode?: string | null;
}

/**
 * Sessions for ONE service track, filtered in the query — not in the UI.
 * Filtering client-side would leave counts computed over the wrong rows.
 */
export function useModeSessions(trainerId: string | undefined, mode: ServiceMode) {
  const { training_mode, training_type } = splitMode(mode);
  return useQuery({
    queryKey: ["trainer-mode-sessions", trainerId, mode],
    enabled: !!trainerId,
    queryFn: async (): Promise<ModeSession[]> => {
      // service_mode is a generated column (20260825170000). Fall back to the
      // mode/type pair when that migration hasn't been run yet.
      let { data, error } = await (supabase as any)
        .from("training_sessions").select("*").neq("status", "cancelled")
        .eq("trainer_id", trainerId).eq("service_mode", mode)
        .order("session_date", { ascending: true });

      if (error) {
        // Pre-migration: training_type is still null on legacy rows, so filter
        // by mode in the query and resolve the track the same way the column
        // will once it exists (null type = the historical group model).
        const res = await (supabase as any)
          .from("training_sessions").select("*").neq("status", "cancelled")
          .eq("trainer_id", trainerId)
          .eq("training_mode", training_mode)
          .order("session_date", { ascending: true });
        if (res.error) return [];
        data = (res.data ?? []).filter(
          (r: any) => (r.training_type ?? "group") === training_type,
        );
      }
      return (data ?? []) as ModeSession[];
    },
  });
}

/** Client counts per track, so no total is produced by mixing records. */
export function useModeClientCounts(trainerId: string | undefined) {
  return useQuery({
    queryKey: ["trainer-mode-clients", trainerId],
    enabled: !!trainerId,
    queryFn: async () => {
      // service_mode is generated by 20260825170000; fall back to the pair it
      // is built from so counts stay correct before that migration runs.
      let { data, error } = await (supabase as any)
        .from("plans").select("user_id, service_mode, training_mode, training_type, status")
        .eq("trainer_id", trainerId).eq("status", "active");
      if (error) {
        const res = await (supabase as any)
          .from("plans").select("user_id, training_mode, training_type, status")
          .eq("trainer_id", trainerId).eq("status", "active");
        data = res.data ?? [];
      }

      const byMode: Record<ServiceMode, Set<string>> = {
        offline_group: new Set(), offline_personal: new Set(),
        online_group: new Set(), online_personal: new Set(),
      };
      for (const r of (data ?? []) as any[]) {
        const key = (r.service_mode
          ?? `${r.training_mode ?? "offline"}_${r.training_type ?? "group"}`) as ServiceMode;
        if (byMode[key]) byMode[key].add(r.user_id);
      }

      const counts = Object.fromEntries(
        SERVICE_MODES.map((m) => [m, byMode[m].size]),
      ) as Record<ServiceMode, number>;

      // TOTAL is unique people across tracks — one client training in two
      // modes is one client, not two.
      const unique = new Set<string>();
      SERVICE_MODES.forEach((m) => byMode[m].forEach((id) => unique.add(id)));
      return { counts, total: unique.size };
    },
  });
}

/** Plan sessions still owed to clients in one track. */
export function useModeSessionsRemaining(trainerId: string | undefined, mode: ServiceMode) {
  const { training_mode, training_type } = splitMode(mode);
  return useQuery({
    queryKey: ["trainer-mode-remaining", trainerId, mode],
    enabled: !!trainerId,
    queryFn: async () => {
      let { data, error } = await (supabase as any)
        .from("plans").select("id, total_sessions, service_mode")
        .eq("trainer_id", trainerId).eq("status", "active").eq("service_mode", mode);
      if (error) {
        const res = await (supabase as any)
          .from("plans").select("id, total_sessions, training_mode, training_type")
          .eq("trainer_id", trainerId).eq("status", "active")
          .eq("training_mode", training_mode);
        data = (res.data ?? []).filter((r: any) => (r.training_type ?? "group") === training_type);
      }
      const planIds = (data ?? []).map((r: any) => r.id);
      const total = (data ?? []).reduce((t: number, r: any) => t + Number(r.total_sessions ?? 0), 0);
      if (!planIds.length) return 0;

      const { data: done } = await (supabase as any)
        .from("training_sessions").select("id, plan_id, status, attended").neq("status", "cancelled")
        .in("plan_id", planIds);
      const completed = (done ?? []).filter(
        (s: any) => s.status === "completed" || s.attended === true,
      ).length;
      return Math.max(0, total - completed);
    },
  });
}

/** Sessions actually delivered in one track for a given month. */
export function monthlyCount(sessions: ModeSession[], monthKey: string) {
  return sessions.filter(
    (s) => s.session_date.slice(0, 7) === monthKey &&
      (s.status === "completed" || s.attended === true),
  ).length;
}
