#!/usr/bin/env node
/**
 * Generate a weekly SEO report (markdown) from Search Console data.
 *
 * Usage:
 *   node scripts/seo/generate-report.mjs          # last 7 days
 *   node scripts/seo/generate-report.mjs 28        # last 28 days
 */
import { google } from "googleapis";
import { getAuthClient, SITE, SITE_HTTPS } from "./auth.mjs";
import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SCOPES = ["https://www.googleapis.com/auth/webmasters.readonly"];

function dateStr(d) { return d.toISOString().slice(0, 10); }

async function main() {
  const days = parseInt(process.argv[2] || "7", 10);
  const end = new Date();
  const start = new Date(end);
  start.setDate(start.getDate() - days);

  // Also fetch previous period for comparison
  const prevEnd = new Date(start);
  prevEnd.setDate(prevEnd.getDate() - 1);
  const prevStart = new Date(prevEnd);
  prevStart.setDate(prevStart.getDate() - days);

  const auth = await getAuthClient(SCOPES);
  const sc = google.searchconsole({ version: "v1", auth });

  const fetchSummary = async (s, e) => {
    const { data } = await sc.searchanalytics.query({
      siteUrl: SITE,
      requestBody: { startDate: dateStr(s), endDate: dateStr(e) },
    });
    return data.rows?.[0] || { clicks: 0, impressions: 0, ctr: 0, position: 0 };
  };

  const fetchDimension = async (dim, s, e, limit = 10) => {
    const { data } = await sc.searchanalytics.query({
      siteUrl: SITE,
      requestBody: {
        startDate: dateStr(s), endDate: dateStr(e),
        dimensions: [dim], rowLimit: limit,
        orderBy: [{ field: "clicks", sortOrder: "DESCENDING" }],
      },
    });
    return data.rows || [];
  };

  console.log(`\n📝 Generating SEO report for ${dateStr(start)} → ${dateStr(end)}...\n`);

  const [curr, prev, topPages, topQueries, devices, countries] = await Promise.all([
    fetchSummary(start, end),
    fetchSummary(prevStart, prevEnd),
    fetchDimension("page", start, end, 15),
    fetchDimension("query", start, end, 15),
    fetchDimension("device", start, end, 5),
    fetchDimension("country", start, end, 10),
  ]);

  const delta = (a, b) => {
    if (b === 0) return a > 0 ? "+∞" : "0";
    const pct = ((a - b) / b * 100).toFixed(1);
    return pct > 0 ? `+${pct}%` : `${pct}%`;
  };

  // Build markdown report
  let md = `# 📊 FitVed SEO Report\n\n`;
  md += `**Period:** ${dateStr(start)} → ${dateStr(end)} (${days} days)  \n`;
  md += `**Generated:** ${new Date().toISOString().slice(0, 19).replace("T", " ")} IST  \n`;
  md += `**Site:** ${SITE}\n\n`;

  md += `## Overall Performance\n\n`;
  md += `| Metric | This Period | Previous Period | Change |\n`;
  md += `|--------|------------|----------------|--------|\n`;
  md += `| **Clicks** | ${curr.clicks} | ${prev.clicks} | ${delta(curr.clicks, prev.clicks)} |\n`;
  md += `| **Impressions** | ${curr.impressions} | ${prev.impressions} | ${delta(curr.impressions, prev.impressions)} |\n`;
  md += `| **CTR** | ${(curr.ctr * 100).toFixed(2)}% | ${(prev.ctr * 100).toFixed(2)}% | ${delta(curr.ctr, prev.ctr)} |\n`;
  md += `| **Avg Position** | ${curr.position.toFixed(1)} | ${prev.position.toFixed(1)} | ${delta(prev.position, curr.position)} |\n\n`;

  md += `## Top Pages\n\n`;
  md += `| Page | Clicks | Impressions | CTR | Position |\n`;
  md += `|------|--------|-------------|-----|----------|\n`;
  for (const r of topPages) {
    const page = r.keys[0].replace(SITE, "") || "/";
    md += `| ${page} | ${r.clicks} | ${r.impressions} | ${(r.ctr * 100).toFixed(1)}% | ${r.position.toFixed(1)} |\n`;
  }

  md += `\n## Top Search Queries\n\n`;
  md += `| Query | Clicks | Impressions | CTR | Position |\n`;
  md += `|-------|--------|-------------|-----|----------|\n`;
  for (const r of topQueries) {
    md += `| ${r.keys[0]} | ${r.clicks} | ${r.impressions} | ${(r.ctr * 100).toFixed(1)}% | ${r.position.toFixed(1)} |\n`;
  }

  md += `\n## Device Breakdown\n\n`;
  md += `| Device | Clicks | Impressions | CTR | Position |\n`;
  md += `|--------|--------|-------------|-----|----------|\n`;
  for (const r of devices) {
    md += `| ${r.keys[0]} | ${r.clicks} | ${r.impressions} | ${(r.ctr * 100).toFixed(1)}% | ${r.position.toFixed(1)} |\n`;
  }

  md += `\n## Top Countries\n\n`;
  md += `| Country | Clicks | Impressions | CTR | Position |\n`;
  md += `|---------|--------|-------------|-----|----------|\n`;
  for (const r of countries) {
    md += `| ${r.keys[0]} | ${r.clicks} | ${r.impressions} | ${(r.ctr * 100).toFixed(1)}% | ${r.position.toFixed(1)} |\n`;
  }

  md += `\n---\n*Auto-generated by FitVed SEO Bot*\n`;

  const reportPath = resolve(__dirname, "../../seo-weekly-report.md");
  writeFileSync(reportPath, md);
  console.log(`✅ Report saved to seo-weekly-report.md`);
  console.log(md);
}

main().catch((err) => {
  if (err.code === 403) {
    console.error("❌ Permission denied. Add the service account email as Owner in Search Console.");
  } else {
    console.error("❌ Error:", err.message);
  }
  process.exit(1);
});
