/**
 * Concise, natural, editorial display titles for blog archive, search, and recommendation UI.
 * Replaces programmatic template titles like "Complete Indian Diet Guide for X"
 * with human-sounding 4-9 word titles while preserving full SEO titles & canonical URLs.
 */

export const EDITORIAL_DISPLAY_TITLES: Record<string, Record<string, string>> = {
  nutrition: {
    "Busy IT Professionals": "Office Diet for IT Professionals",
    "Vegetarians": "Indian Vegetarian Diet: Complete Guide",
    "Beginners Over 30": "Eating Well After 30: Indian Diet Guide",
    "Desk Workers": "Desk Job Diet: What to Eat",
    "Post-Workout Recovery": "Nutrition for Post-Workout Recovery",
    "Fat Burning": "Indian Diet for Fat Loss",
    "Hormonal Balance": "Eating for Hormonal Health",
    "Metabolic Flexibility": "Metabolic Flexibility: Indian Diet Guide",
    "Muscle Retention": "Muscle-Preserving Indian Diet",
    "Energy Boost": "Indian Foods for Better Energy",
    "Night Shift Workers": "Night Shift Diet: What to Eat",
    "Budget Meal Planning": "Budget-Friendly Indian Meal Plan"
  },
  'weight-loss': {
    'Busy IT Professionals': 'Lose Fat Without Giving Up Desk Meals',
    'Vegetarians': 'Vegetarian Fat Loss That Works',
    'Beginners Over 30': 'Drop Belly Fat After 30',
    'Desk Workers': 'Sedentary Fat Loss Strategy',
    'Post-Workout Recovery': 'Fat Loss and Muscle Recovery',
    'Fat Burning': 'Indian Home Foods for Belly Fat Loss',
    'Hormonal Balance': 'Hormone-Friendly Fat Loss Meals',
    'Metabolic Flexibility': 'Burn Fat Without Constant Hunger',
    'Muscle Retention': 'Lose Fat, Not Lean Muscle',
    'Energy Boost': 'Fat Loss Without Constant Fatigue',
    'Night Shift Workers': 'Weight Loss Strategy for Night Shifts',
    'Budget Meal Planning': 'Lose Weight on an Indian Grocery Budget'
  },
  'muscle-gain': {
    'Busy IT Professionals': 'Build Muscle on a Tight Schedule',
    'Vegetarians': 'Plant-Based Muscle Building Guide',
    'Beginners Over 30': 'Build Lean Muscle After 30',
    'Desk Workers': 'Muscle Hypertrophy for Desk Sitters',
    'Post-Workout Recovery': 'Post-Lifting Muscle Growth Essentials',
    'Fat Burning': 'Recomposition: Gain Muscle While Burning Fat',
    'Hormonal Balance': 'Hormones and Muscle Growth Simplified',
    'Metabolic Flexibility': 'Fueling Hypertrophy with Smart Carbs',
    'Muscle Retention': 'Maximizing Muscle Synthesis Daily',
    'Energy Boost': 'High-Energy Lifting and Nutrition Blueprint',
    'Night Shift Workers': 'Building Muscle Around Shift Work',
    'Budget Meal Planning': 'Budget High-Protein Muscle Growth'
  },
  protein: {
    'Busy IT Professionals': 'Quick High-Protein Desk Snacks in India',
    'Vegetarians': 'Top Vegetarian Protein Sources Ranked',
    'Beginners Over 30': 'Daily Protein Needs for Adults Over 30',
    'Desk Workers': 'Convenient High-Protein Foods for Sitting All Day',
    'Post-Workout Recovery': 'Best Post-Workout Protein Choices',
    'Fat Burning': 'High-Protein Foods That Fire Up Metabolism',
    'Hormonal Balance': 'Protein for Hormonal and Metabolic Health',
    'Metabolic Flexibility': 'Protein-First Meal Structuring',
    'Muscle Retention': 'Leucine-Rich Indian Protein Foods',
    'Energy Boost': 'Protein-Rich Foods for All-Day Stamina',
    'Night Shift Workers': 'Easy Night Shift Protein Options',
    'Budget Meal Planning': 'Cheapest High-Protein Foods in India'
  },
  recipes: {
    'Busy IT Professionals': '15-Minute Protein Meals for Busy Workdays',
    'Vegetarians': 'Quick High-Protein Vegetarian Dishes',
    'Beginners Over 30': 'Nutrient-Dense Easy Indian Recipes',
    'Desk Workers': 'Light Desk-Friendly Lunch Recipes',
    'Post-Workout Recovery': 'Fast Post-Workout Meals and Shakes',
    'Fat Burning': 'Low-Calorie High-Volume Indian Recipes',
    'Hormonal Balance': 'Hormone-Nourishing Recipe Ideas',
    'Metabolic Flexibility': 'Smart Carb-Periodized Meal Options',
    'Muscle Retention': 'Protein-Packed Daily Dishes',
    'Energy Boost': 'Recipes to Beat the Midday Energy Slump',
    'Night Shift Workers': 'Easy 2 AM Night Shift Snacks',
    'Budget Meal Planning': 'Affordable High-Protein Batch Recipes'
  },
  supplements: {
    'Busy IT Professionals': 'Supplements for High-Stress Workdays',
    'Vegetarians': 'Plant-Based Supplement Guide for Vegetarians',
    'Beginners Over 30': 'Essential Supplements for Adults Over 30',
    'Desk Workers': 'Supplements for Sedentary Desk Workers',
    'Post-Workout Recovery': 'Post-Workout Recovery Supplements That Work',
    'Fat Burning': 'Supplements to Support Fat Loss & Metabolism',
    'Hormonal Balance': 'Supplements for Hormonal Balance',
    'Metabolic Flexibility': 'Supplements for Metabolic Health',
    'Muscle Retention': 'Supplements to Retain Muscle During Weight Loss',
    'Energy Boost': 'Natural Supplements for All-Day Stamina',
    'Night Shift Workers': 'Supplements for Night Shift Sleep & Energy',
    'Budget Meal Planning': 'Most Cost-Effective Supplements in India'
  },
  'womens-health': {
    'Busy IT Professionals': 'Women in Tech: Staying Fit at Desk Jobs',
    'Vegetarians': 'Vegetarian Women\'s Health & Iron Guide',
    'Beginners Over 30': 'Women\'s Health & Vitality After 30',
    'Desk Workers': 'Posture & Wellness for Female Desk Workers',
    'Post-Workout Recovery': 'Exercise Recovery Strategy for Women',
    'Fat Burning': 'Fat Loss Blueprint for Women',
    'Hormonal Balance': 'Balancing Hormones through Indian Foods',
    'Metabolic Flexibility': 'Metabolic Health Blueprint for Women',
    'Muscle Retention': 'Preserving Strength & Muscle for Women',
    'Energy Boost': 'Overcoming Fatigue in Busy Women',
    'Night Shift Workers': 'Managing Night Shifts as a Working Woman',
    'Budget Meal Planning': 'Affordable Women\'s Wellness Habits'
  },
  pcos: {
    'Busy IT Professionals': 'Managing PCOS at a 9-to-5 Desk Job',
    'Vegetarians': 'PCOS Diet Plan for Vegetarians',
    'Beginners Over 30': 'PCOS Management After 30',
    'Desk Workers': 'PCOS Exercises for Desk Workers',
    'Post-Workout Recovery': 'Post-Workout PCOS Recovery Essentials',
    'Fat Burning': 'Reversing PCOS Insulin Resistance & Weight',
    'Hormonal Balance': 'Balanced Hormone Protocols for PCOS',
    'Metabolic Flexibility': 'Metabolic Flexibility & PCOS Control',
    'Muscle Retention': 'Retaining Muscle on a PCOS Diet',
    'Energy Boost': 'Boosting Energy Levels with PCOS',
    'Night Shift Workers': 'Managing PCOS on Night Shift Schedules',
    'Budget Meal Planning': 'Budget-Friendly PCOS Meal Blueprint'
  },
  diabetes: {
    'Busy IT Professionals': 'Blood Sugar Control for Busy Desk Workers',
    'Vegetarians': 'Vegetarian Blood Sugar Management',
    'Beginners Over 30': 'Managing HbA1c Levels After 30',
    'Desk Workers': 'Preventing Spikes While Sitting All Day',
    'Post-Workout Recovery': 'Exercise & Blood Sugar Recovery',
    'Fat Burning': 'Fat Loss Strategies for Type-2 Diabetes',
    'Hormonal Balance': 'Hormonal Balance & Insulin Sensitivity',
    'Metabolic Flexibility': 'Improving Metabolic Flexibility in Diabetes',
    'Muscle Retention': 'Preserving Muscle Mass with High Blood Sugar',
    'Energy Boost': 'Beating Diabetic Fatigue Naturally',
    'Night Shift Workers': 'Managing Blood Sugar During Night Shifts',
    'Budget Meal Planning': 'Affordable Diabetes-Friendly Indian Foods'
  },
  'heart-health': {
    'Busy IT Professionals': 'Heart Health for Busy IT Professionals',
    'Vegetarians': 'Plant-Based Foods for Heart & Lipid Health',
    'Beginners Over 30': 'Cardiovascular Wellness After 30',
    'Desk Workers': 'Protecting Your Heart When Sitting All Day',
    'Post-Workout Recovery': 'Post-Exercise Heart & Circulation Recovery',
    'Fat Burning': 'Fat Loss for Better Cholesterol & Heart Health',
    'Hormonal Balance': 'Hormonal Health & Heart Vitality',
    'Metabolic Flexibility': 'Metabolic Health for a Strong Heart',
    'Muscle Retention': 'Maintaining Heart Health & Muscle Tone',
    'Energy Boost': 'Cardiovascular Energy & Stamina Boosters',
    'Night Shift Workers': 'Cardio Health Strategy for Shift Workers',
    'Budget Meal Planning': 'Budget Foods for a Healthy Heart'
  },
  longevity: {
    'Busy IT Professionals': 'Longevity Strategies for Busy Professionals',
    'Vegetarians': 'Plant-Based Diets for Healthy Aging',
    'Beginners Over 30': 'Cellular Vitality Blueprint After 30',
    'Desk Workers': 'Combating Sedentary Aging at Desk Jobs',
    'Post-Workout Recovery': 'Recovery Protocols for Anti-Aging',
    'Fat Burning': 'Fat Loss for Metabolic Longevity',
    'Hormonal Balance': 'Hormone Optimization as You Age',
    'Metabolic Flexibility': 'Metabolic Flexibility for Lifelong Health',
    'Muscle Retention': 'Preserving Muscle for Lifelong Strength',
    'Energy Boost': 'Sustained Daily Energy for Longevity',
    'Night Shift Workers': 'Circadian Health & Longevity on Night Shifts',
    'Budget Meal Planning': 'Affordable Anti-Aging Indian Foods'
  },
  sleep: {
    'Busy IT Professionals': 'Sleep Strategy for High-Stress Jobs',
    'Vegetarians': 'Plant-Based Foods for Better Sleep',
    'Beginners Over 30': 'Optimizing Sleep Architecture After 30',
    'Desk Workers': 'Sleeping Better After Long Sitting Days',
    'Post-Workout Recovery': 'Post-Workout Sleep & Tissue Repair',
    'Fat Burning': 'Sleep Optimization for Fat Loss',
    'Hormonal Balance': 'Sleep & Hormone Regulation Blueprint',
    'Metabolic Flexibility': 'Metabolic Benefits of Quality Rest',
    'Muscle Retention': 'Sleep Protocols for Muscle Retention',
    'Energy Boost': 'Restorative Sleep for All-Day Energy',
    'Night Shift Workers': 'Mastering Sleep on Night Shift Schedules',
    'Budget Meal Planning': 'Low-Cost Habits for Deep Restorative Sleep'
  },
  stress: {
    'Busy IT Professionals': 'De-Stressing After Long Workdays',
    'Vegetarians': 'Plant-Based Foods That Reduce Stress',
    'Beginners Over 30': 'Managing Cortisol Levels After 30',
    'Desk Workers': 'Relieving Stress at Your Office Desk',
    'Post-Workout Recovery': 'Stress Recovery for Active Adults',
    'Fat Burning': 'Managing Stress-Induced Weight Gain',
    'Hormonal Balance': 'Cortisol Balance for Hormonal Harmony',
    'Metabolic Flexibility': 'Stress & Metabolic Health Essentials',
    'Muscle Retention': 'Protecting Muscle from Stress & Cortisol',
    'Energy Boost': 'Overcoming Chronic Stress & Brain Fog',
    'Night Shift Workers': 'Stress Management for Night Shift Workers',
    'Budget Meal Planning': 'Free & Low-Cost Daily Stress Fixes'
  },
  'workplace-fitness': {
    'Busy IT Professionals': 'Desk Ergonomics for Software Engineers',
    'Vegetarians': 'Vegetarian Lunchbox Ideas for Work',
    'Beginners Over 30': 'Workplace Fitness for Adults Over 30',
    'Desk Workers': '5-Minute Desk Stretching Routines',
    'Post-Workout Recovery': 'Post-Work Recovery After Office Hours',
    'Fat Burning': 'Desk-Worker Fat Loss Action Plan',
    'Hormonal Balance': 'Workplace Wellness & Hormonal Balance',
    'Metabolic Flexibility': 'Metabolic Health at Your Workstation',
    'Muscle Retention': 'Retaining Muscle with Office Desk Jobs',
    'Energy Boost': 'Beating 3 PM Office Slumps',
    'Night Shift Workers': 'Workplace Fitness for Night Shift Teams',
    'Budget Meal Planning': 'Budget Workstation Health Hacks'
  },
  'home-workouts': {
    'Busy IT Professionals': '20-Minute Home Workouts Between Meetings',
    'Vegetarians': 'No-Equipment Workouts for Vegetarians',
    'Beginners Over 30': 'At-Home Strength Training After 30',
    'Desk Workers': 'Quick Home Workouts for Desk Workers',
    'Post-Workout Recovery': 'Home Workout Recovery Techniques',
    'Fat Burning': 'At-Home Caloric Burn Blueprint',
    'Hormonal Balance': 'Home Fitness for Hormonal Harmony',
    'Metabolic Flexibility': 'Metabolic Conditioning at Home',
    'Muscle Retention': 'Building & Retaining Muscle at Home',
    'Energy Boost': 'Quick Home Workouts for Fast Energy',
    'Night Shift Workers': 'Night Shift Home Workout Schedules',
    'Budget Meal Planning': 'Zero-Cost Home Workout Guide'
  },
  gym: {
    'Busy IT Professionals': 'Gym Routines for Busy Schedules',
    'Vegetarians': 'Gym Workouts for Vegetarian Lifters',
    'Beginners Over 30': 'Smart Weight Training After 30',
    'Desk Workers': 'Gym Setup Guide for Desk Sitters',
    'Post-Workout Recovery': 'Post-Gym Recovery & Muscle Repair',
    'Fat Burning': 'Gym Workouts for Maximum Fat Loss',
    'Hormonal Balance': 'Hormone-Optimized Weight Training',
    'Metabolic Flexibility': 'Fueling Heavy Gym Lifts Effortlessly',
    'Muscle Retention': 'Gym Hypertrophy & Muscle Retention',
    'Energy Boost': 'High-Energy Gym Training Protocols',
    'Night Shift Workers': 'Gym Workout Timings for Night Shifters',
    'Budget Meal Planning': 'Budget Gym Workouts & Gear Hacks'
  },
  yoga: {
    'Busy IT Professionals': 'Desk Yoga to Relieve Tech Stress',
    'Vegetarians': 'Gentle Yoga for Vegetarian Wellness',
    'Beginners Over 30': 'Daily Yoga & Flexibility After 30',
    'Desk Workers': 'Desk Yoga Exercises for Posture',
    'Post-Workout Recovery': 'Post-Workout Yoga Recovery Flow',
    'Fat Burning': 'Yoga Protocols for Weight Management',
    'Hormonal Balance': 'Yoga for Hormonal Balance & Calm',
    'Metabolic Flexibility': 'Yoga for Metabolic & Digestive Health',
    'Muscle Retention': 'Yoga for Core & Muscle Stability',
    'Energy Boost': 'Morning Yoga for Instant Energy',
    'Night Shift Workers': 'Yoga for Night Shift Sleep & Relaxation',
    'Budget Meal Planning': 'Free Daily Home Yoga Practice Guide'
  },
  running: {
    'Busy IT Professionals': 'How to Train for a 5K on a Tight Schedule',
    'Vegetarians': 'Plant-Based Fueling for Runners',
    'Beginners Over 30': 'Running Safely After Age 30',
    'Desk Workers': 'Running Strategy for Desk Sitters',
    'Post-Workout Recovery': 'Post-Run Recovery Protocols',
    'Fat Burning': 'Running for Efficient Fat Loss',
    'Hormonal Balance': 'Running & Hormonal Balance Essentials',
    'Metabolic Flexibility': 'Metabolic Fueling for Long Distance Runs',
    'Muscle Retention': 'Retaining Muscle Mass as a Runner',
    'Energy Boost': 'Running for All-Day Stamina & Focus',
    'Night Shift Workers': 'Running Schedules for Night Workers',
    'Budget Meal Planning': 'Budget-Friendly Running & Footwear Tips'
  },
  mobility: {
    'Busy IT Professionals': '5-Minute Hip Mobility for Desk Sitters',
    'Vegetarians': 'Mobility Routines for Vegetarian Fitness',
    'Beginners Over 30': 'Joint & Hip Mobility After 30',
    'Desk Workers': 'Desk Sitting Mobility & Posture Hacks',
    'Post-Workout Recovery': 'Post-Workout Joint Mobility Drills',
    'Fat Burning': 'Mobility Exercises for Fat Loss Workouts',
    'Hormonal Balance': 'Mobility Protocols for Hormonal Ease',
    'Metabolic Flexibility': 'Mobility Work for Better Movement',
    'Muscle Retention': 'Protecting Joints & Retaining Muscle',
    'Energy Boost': 'Mobility Drills for Morning Energy',
    'Night Shift Workers': 'Mobility Training for Shift Workers',
    'Budget Meal Planning': 'Daily 10-Minute Zero-Cost Mobility Flow'
  },
  recovery: {
    'Busy IT Professionals': 'Faster Recovery for Busy Workout Schedules',
    'Vegetarians': 'Plant-Based Recovery Foods & Drinks',
    'Beginners Over 30': 'Muscle Recovery & Joint Care After 30',
    'Desk Workers': 'Recovery Exercises for Desk Workers',
    'Post-Workout Recovery': 'DOMS Relief & Muscle Recovery Guide',
    'Fat Burning': 'Recovery Strategies During Fat Loss',
    'Hormonal Balance': 'Hormonal Balance & Deep Recovery',
    'Metabolic Flexibility': 'Metabolic Recovery Between Workouts',
    'Muscle Retention': 'Speeding Up Muscle Protein Synthesis',
    'Energy Boost': 'Restoring Energy After Intense Lifts',
    'Night Shift Workers': 'Recovery Protocols for Night Shift Lifters',
    'Budget Meal Planning': 'Budget Muscle Recovery Hacks'
  },
  injuries: {
    'Busy IT Professionals': 'Preventing Lower Back Pain from Long Sitting',
    'Vegetarians': 'Plant-Based Nutrition for Injury Rehab',
    'Beginners Over 30': 'Injury Prevention & Joint Care After 30',
    'Desk Workers': 'Rehab Exercises for Sitting Strain',
    'Post-Workout Recovery': 'Post-Injury Workout Recovery Guide',
    'Fat Burning': 'Safe Fat Loss Workouts During Rehab',
    'Hormonal Balance': 'Hormonal Health & Tissue Healing',
    'Metabolic Flexibility': 'Metabolic Health During Injury Rehab',
    'Muscle Retention': 'Retaining Muscle Mass While Injured',
    'Energy Boost': 'Rebuilding Energy After Injury Break',
    'Night Shift Workers': 'Rehab Exercises for Night Shift Workers',
    'Budget Meal Planning': 'At-Home Zero-Cost Injury Prevention'
  },
  creatine: {
    'Busy IT Professionals': 'Should Desk Workers Take Creatine?',
    'Vegetarians': 'Creatine Guide for Vegetarians',
    'Beginners Over 30': 'Creatine Benefits for Adults Over 30',
    'Desk Workers': 'Creatine Monohydrate for Desk Sitters',
    'Post-Workout Recovery': 'Creatine for Post-Workout Muscle Recovery',
    'Fat Burning': 'Creatine Use During Fat Loss Cycles',
    'Hormonal Balance': 'Creatine and Hormonal Health Facts',
    'Metabolic Flexibility': 'Creatine for Cellular Energy & Metabolism',
    'Muscle Retention': 'Creatine Loading for Muscle Retention',
    'Energy Boost': 'Creatine Monohydrate for Mental Alertness',
    'Night Shift Workers': 'Creatine Timing for Night Shift Workers',
    'Budget Meal Planning': 'Most Cost-Effective Creatine Brands in India'
  },
  'whey-protein': {
    'Busy IT Professionals': 'Whey Isolate vs Concentrate for Fast Meals',
    'Vegetarians': 'Whey Protein Selection for Vegetarians',
    'Beginners Over 30': 'Whey Protein Supplementation After 30',
    'Desk Workers': 'Easy Whey Shakes for Desk Workers',
    'Post-Workout Recovery': 'Post-Workout Whey Protein Pacing',
    'Fat Burning': 'Whey Protein for Caloric Deficits',
    'Hormonal Balance': 'Whey Protein & Hormonal Digestion',
    'Metabolic Flexibility': 'Whey Protein for Metabolic Support',
    'Muscle Retention': 'Whey Isolate for Muscle Retention',
    'Energy Boost': 'Whey Protein Shakes for Quick Energy',
    'Night Shift Workers': 'Whey Protein Timing for Shift Workers',
    'Budget Meal Planning': 'Cheapest High-Quality Whey Protein in India'
  },
  vitamins: {
    'Busy IT Professionals': 'Fixing Vitamin D Deficiencies in AC Offices',
    'Vegetarians': 'Essential Vitamins for Vegetarian Diets',
    'Beginners Over 30': 'Vitamin D3 & B12 Needs After 30',
    'Desk Workers': 'Vitamins for Sedentary Desk Workers',
    'Post-Workout Recovery': 'Vitamins for Exercise Recovery',
    'Fat Burning': 'Vitamin Deficiency & Weight Loss Plateaus',
    'Hormonal Balance': 'Vitamins for Hormonal Regulation',
    'Metabolic Flexibility': 'Vitamins for Metabolic Efficiency',
    'Muscle Retention': 'Vitamins for Muscle Health & Function',
    'Energy Boost': 'Vitamins for Brain Fog & Chronic Fatigue',
    'Night Shift Workers': 'Vitamin Protocols for Night Shift Workers',
    'Budget Meal Planning': 'Budget-Friendly Vitamin Sources in India'
  },
  'fat-loss': {
    'Busy IT Professionals': 'Smart Fat Loss for Sedentary Professionals',
    'Vegetarians': 'Vegetarian Fat Loss Blueprint',
    'Beginners Over 30': 'Sustainable Fat Loss After 30',
    'Desk Workers': 'Fat Loss Protocols for Sitting All Day',
    'Post-Workout Recovery': 'Fat Loss & Muscle Preservation Balance',
    'Fat Burning': 'Accelerating Fat Loss Safely at Home',
    'Hormonal Balance': 'Fat Loss & Hormonal Health Balance',
    'Metabolic Flexibility': 'Boosting Metabolic Rate for Fat Loss',
    'Muscle Retention': 'Keeping Muscle While Dropping Body Fat',
    'Energy Boost': 'Fat Loss Without Dropping Energy Levels',
    'Night Shift Workers': 'Fat Loss Blueprint for Shift Workers',
    'Budget Meal Planning': 'Affordable High-Volume Fat Loss Foods'
  },
  'beginner-guides': {
    'Busy IT Professionals': 'Fitness Blueprint for Busy Beginners',
    'Vegetarians': 'Beginner\'s Fitness Guide for Vegetarians',
    'Beginners Over 30': 'Starting Your Fitness Journey After 30',
    'Desk Workers': 'Beginner Workout Guide for Desk Sitters',
    'Post-Workout Recovery': 'Beginner Recovery & Muscle Soreness',
    'Fat Burning': 'Beginner Blueprint for Sustainable Fat Loss',
    'Hormonal Balance': 'Beginner Guide to Hormonal Health',
    'Metabolic Flexibility': 'Understanding Metabolism as a Beginner',
    'Muscle Retention': 'Beginner Muscle Retention Basics',
    'Energy Boost': 'Beginner Guide to All-Day Stamina',
    'Night Shift Workers': 'Beginner Fitness Plan for Night Shifters',
    'Budget Meal Planning': 'Budget Beginner Fitness Blueprint'
  },
  'senior-fitness': {
    'Busy IT Professionals': 'Staying Fit After 40 in High-Stress Jobs',
    'Vegetarians': 'Vegetarian Active Aging & Bone Density',
    'Beginners Over 30': 'Building Strength & Mobility After 40',
    'Desk Workers': 'Senior Fitness Drills for Desk Workers',
    'Post-Workout Recovery': 'Active Aging Recovery & Joint Health',
    'Fat Burning': 'Weight Management for Adults Over 40',
    'Hormonal Balance': 'Hormones & Vitality After 40',
    'Metabolic Flexibility': 'Metabolic Health in Active Aging',
    'Muscle Retention': 'Preserving Muscle Mass After 40',
    'Energy Boost': 'Boosting Energy & Vitality After 40',
    'Night Shift Workers': 'Active Aging Routines for Shift Workers',
    'Budget Meal Planning': 'Affordable Fitness Habits for Older Adults'
  },
  'kids-nutrition': {
    'Busy IT Professionals': 'Quick Healthy Tiffins for Busy Parents',
    'Vegetarians': 'Vegetarian Kid-Friendly Protein Hacks',
    'Beginners Over 30': 'Nutrition Essentials for Growing Children',
    'Desk Workers': 'Healthy Eating Habits for Sitting Students',
    'Post-Workout Recovery': 'Childhood Recovery & Activity Nutrition',
    'Fat Burning': 'Healthy Weight Management for Children',
    'Hormonal Balance': 'Balanced Hormones & Child Growth',
    'Metabolic Flexibility': 'Metabolic Health in Growing Kids',
    'Muscle Retention': 'Protein & Nutrient Needs for Kids',
    'Energy Boost': 'Healthy Morning Foods for Student Energy',
    'Night Shift Workers': 'Managing Meals for Shift-Worker Parents',
    'Budget Meal Planning': 'Budget Healthy School Snack Ideas'
  },
  'corporate-wellness': {
    'Busy IT Professionals': 'Corporate Health Strategies for Tech Teams',
    'Vegetarians': 'Vegetarian Corporate Wellness Meals',
    'Beginners Over 30': 'Corporate Wellness Programs After 30',
    'Desk Workers': 'Office Desk Health & Posture Programs',
    'Post-Workout Recovery': 'Employee Recovery & Wellness Protocols',
    'Fat Burning': 'Corporate Fat Loss & Health Challenges',
    'Hormonal Balance': 'Hormonal & Stress Relief in Corporate Life',
    'Metabolic Flexibility': 'Corporate Executive Metabolic Health',
    'Muscle Retention': 'Retaining Strength in Corporate Jobs',
    'Energy Boost': 'Boosting Employee Energy & Focus',
    'Night Shift Workers': 'Corporate Wellness for Night Shift Teams',
    'Budget Meal Planning': 'Cost-Effective Corporate Wellness Hacks'
  },
  pregnancy: {
    'Busy IT Professionals': 'Working Through Pregnancy in Tech Jobs',
    'Vegetarians': 'Vegetarian Prenatal Nutrition Essentials',
    'Beginners Over 30': 'Safe Exercise & Nutrition During Pregnancy',
    'Desk Workers': 'Desk Comfort & Posture During Pregnancy',
    'Post-Workout Recovery': 'Post-Exercise Recovery During Pregnancy',
    'Fat Burning': 'Healthy Weight Management in Pregnancy',
    'Hormonal Balance': 'Hormonal Changes During Pregnancy',
    'Metabolic Flexibility': 'Metabolic Health for Expectant Mothers',
    'Muscle Retention': 'Preserving Muscle Strength in Pregnancy',
    'Energy Boost': 'Maintaining Energy During Pregnancy',
    'Night Shift Workers': 'Managing Pregnancy on Shift Schedules',
    'Budget Meal Planning': 'Budget-Friendly Prenatal Nutrition'
  },
  postpartum: {
    'Busy IT Professionals': 'Returning to Work & Rebuilding Core Strength',
    'Vegetarians': 'Vegetarian Postpartum Recovery Nutrition',
    'Beginners Over 30': 'Rebuilding Muscle & Strength Postpartum',
    'Desk Workers': 'Postpartum Core Rehab for Desk Sitters',
    'Post-Workout Recovery': 'Postpartum Muscle & Tissue Recovery',
    'Fat Burning': 'Safe Postpartum Fat Loss Blueprint',
    'Hormonal Balance': 'Postpartum Hormonal Recovery Guide',
    'Metabolic Flexibility': 'Metabolic Recovery After Childbirth',
    'Muscle Retention': 'Diastasis Recti & Core Rehabilitation',
    'Energy Boost': 'Beating Postpartum Fatigue Naturally',
    'Night Shift Workers': 'Postpartum Care for Shift-Worker Mothers',
    'Budget Meal Planning': 'Affordable Postpartum Recovery Advice'
  },
  'mens-health': {
    'Busy IT Professionals': 'Maintaining Energy & Testosterone at Work',
    'Vegetarians': 'Vegetarian Men\'s Health & Protein Guide',
    'Beginners Over 30': 'Men\'s Health & Vitality After 30',
    'Desk Workers': 'Posture & Health for Male Desk Workers',
    'Post-Workout Recovery': 'Exercise Recovery Strategy for Men',
    'Fat Burning': 'Men\'s Fat Loss & Muscle Preservation',
    'Hormonal Balance': 'Testosterone & Hormonal Health Guide',
    'Metabolic Flexibility': 'Metabolic Optimization for Men',
    'Muscle Retention': 'Building & Retaining Muscle Mass for Men',
    'Energy Boost': 'All-Day Energy & Focus for Men',
    'Night Shift Workers': 'Men\'s Health Plan for Shift Workers',
    'Budget Meal Planning': 'Budget Men\'s Fitness & Meal Guide'
  },
  'gut-health': {
    'Busy IT Professionals': 'Beating Office Bloating & Indigestion',
    'Vegetarians': 'Probiotic Foods for Indian Vegetarians',
    'Beginners Over 30': 'Gut Health & Digestion After 30',
    'Desk Workers': 'Desk Sitting & Digestive Health Hacks',
    'Post-Workout Recovery': 'Gut Health & Exercise Recovery Synergy',
    'Fat Burning': 'Gut Microbes & Weight Management',
    'Hormonal Balance': 'Gut-Hormone Connection Explained',
    'Metabolic Flexibility': 'Improving Metabolism Through Gut Health',
    'Muscle Retention': 'Gut Health for Optimal Nutrient Absorption',
    'Energy Boost': 'Beating Gut Sluggishness & Low Energy',
    'Night Shift Workers': 'Gut Health Protocols for Night Shifts',
    'Budget Meal Planning': 'Cheap Probiotic Indian Superfoods'
  },
  'indian-diets': {
    'Busy IT Professionals': 'Balanced Indian Lunchboxes for Office Days',
    'Vegetarians': 'High-Protein Indian Thali for Vegetarians',
    'Beginners Over 30': 'Indian Meals Calibrated for Adults Over 30',
    'Desk Workers': 'Indian Thalis for Sedentary Desk Workers',
    'Post-Workout Recovery': 'Post-Workout Indian Thali Meal Structuring',
    'Fat Burning': 'Indian Home Food Blueprint for Fat Loss',
    'Hormonal Balance': 'Indian Diet Hacks for Hormonal Health',
    'Metabolic Flexibility': 'Metabolic Flexibility with Indian Meals',
    'Muscle Retention': 'Preserving Muscle on an Indian Diet',
    'Energy Boost': 'High-Energy Indian Meal Combination',
    'Night Shift Workers': 'Indian Diet Plans for Night Shift Workers',
    'Budget Meal Planning': 'Budget-Friendly Indian Thali Blueprint'
  },
  'regional-indian-foods': {
    'Busy IT Professionals': 'Healthy South & North Indian Quick Bites',
    'Vegetarians': 'Protein Content in Dosa, Idli & Sattu',
    'Beginners Over 30': 'Regional Indian Superfoods After 30',
    'Desk Workers': 'Light Regional Dishes for Desk Lunches',
    'Post-Workout Recovery': 'Post-Workout Regional Meal Options',
    'Fat Burning': 'Regional Indian Foods for Fat Loss',
    'Hormonal Balance': 'Regional Indian Ingredients for Hormones',
    'Metabolic Flexibility': 'Metabolic Benefits of Fermented Indian Foods',
    'Muscle Retention': 'High-Protein Regional Indian Foods',
    'Energy Boost': 'Energy-Boosting Regional Beverages',
    'Night Shift Workers': 'Regional Indian Snacks for Night Shifts',
    'Budget Meal Planning': 'Most Economical Regional Indian Foods'
  },
  'meal-plans': {
    'Busy IT Professionals': 'Sunday Batch Cooking for the Work Week',
    'Vegetarians': '7-Day Vegetarian Meal Prep Schedule',
    'Beginners Over 30': '7-Day Meal Plan for Adults Over 30',
    'Desk Workers': '7-Day Meal Prep for Sitting Desk Workers',
    'Post-Workout Recovery': '7-Day Post-Workout Recovery Meal Plan',
    'Fat Burning': '7-Day Fat Loss Meal Plan with Indian Foods',
    'Hormonal Balance': '7-Day Hormonal Balance Meal Blueprint',
    'Metabolic Flexibility': '7-Day Carb-Periodized Meal Plan',
    'Muscle Retention': '7-Day High-Protein Muscle Retention Plan',
    'Energy Boost': '7-Day Energy-Boosting Meal Schedule',
    'Night Shift Workers': '7-Day Meal Plan for Night Shift Workers',
    'Budget Meal Planning': '7-Day Budget Indian Meal Prep Schedule'
  },
  comparisons: {
    'Busy IT Professionals': 'Meal Prep vs Food Delivery: Which is Better?',
    'Vegetarians': 'Paneer vs Soya Chunks for Protein',
    'Beginners Over 30': 'Fitness at 20 vs Fitness After 30',
    'Desk Workers': 'Gym Workouts vs Home Workouts for Sitting Workers',
    'Post-Workout Recovery': 'Whey Protein vs Whole Food Recovery',
    'Fat Burning': 'Keto vs Low-Carb Indian Diet for Fat Loss',
    'Hormonal Balance': 'Hormones vs Caloric Intake in Weight Loss',
    'Metabolic Flexibility': 'High Carb vs Low Carb for Metabolism',
    'Muscle Retention': 'Cardio vs Lifting for Muscle Retention',
    'Energy Boost': 'Coffee vs Sattu Drink for Energy',
    'Night Shift Workers': 'Night Shift vs Day Shift Fitness Strategies',
    'Budget Meal Planning': 'Home Food vs Commercial Protein Foods'
  },
  calculators: {
    'Busy IT Professionals': 'Calculating Your Calories for a Desk Job',
    'Vegetarians': 'Caloric Needs for Vegetarian Diets',
    'Beginners Over 30': 'Calculating Macro Needs After 30',
    'Desk Workers': 'TDEE & Calorie Needs for Desk Workers',
    'Post-Workout Recovery': 'Calculating Post-Workout Macro Ratios',
    'Fat Burning': 'Caloric Deficit Calculations for Fat Loss',
    'Hormonal Balance': 'Macro Counting for Hormonal Health',
    'Metabolic Flexibility': 'Using Calculators for Metabolic Flexibility',
    'Muscle Retention': 'Protein Macro Target Calculator for Muscle',
    'Energy Boost': 'Calculating Energy Needs for Busy Days',
    'Night Shift Workers': 'Calorie & Shift Timing Calculator',
    'Budget Meal Planning': 'Free Calorie & Macro Calculations'
  },
  'bangalore-local-guides': {
    'Busy IT Professionals': 'Personal Fitness Coaching in Whitefield & HSR',
    'Vegetarians': 'Vegetarian Home Fitness Trainers in Bangalore',
    'Beginners Over 30': 'At-Home Personal Fitness in Bangalore After 30',
    'Desk Workers': 'In-Home Personal Coaching for Desk Workers',
    'Post-Workout Recovery': 'Post-Injury & Recovery Coaching in Bangalore',
    'Fat Burning': 'Weight Loss Personal Coaching in Bangalore',
    'Hormonal Balance': 'Hormone & PCOS Fitness Coaching in Bangalore',
    'Metabolic Flexibility': 'Metabolic Fitness Trainers in Bangalore',
    'Muscle Retention': 'Muscle Building At-Home Coaching Bangalore',
    'Energy Boost': 'Energy & Fitness Coaching in Bangalore',
    'Night Shift Workers': 'Night Shift Personal Trainers in Bangalore',
    'Budget Meal Planning': 'Affordable Personal Trainers in Bangalore'
  },
  'nri-fitness': {
    'Busy IT Professionals': 'Staying Fit as an NRI Tech Professional',
    'Vegetarians': 'Maintaining Indian Vegetarian Diets Abroad',
    'Beginners Over 30': 'NRI Fitness & Meal Strategies After 30',
    'Desk Workers': 'Fitness Strategies for NRIs at Desk Jobs',
    'Post-Workout Recovery': 'Post-Workout Recovery Guides for NRIs',
    'Fat Burning': 'NRI Fat Loss Blueprint with Local Foods',
    'Hormonal Balance': 'Hormones & Stress Management for NRIs',
    'Metabolic Flexibility': 'Metabolic Flexibility for NRIs Abroad',
    'Muscle Retention': 'Retaining Muscle While Living Abroad',
    'Energy Boost': 'Boosting Energy Levels on NRI Schedules',
    'Night Shift Workers': 'NRI Fitness Routines for Night Shifts',
    'Budget Meal Planning': 'Budget Fitness & Groceries for NRIs'
  },
  'healthy-habits': {
    'Busy IT Professionals': 'Building 30-Day Fitness Habits at Work',
    'Vegetarians': '30-Day Vegetarian Health Habit Stacking',
    'Beginners Over 30': 'Habit Stacking & Fitness Consistency After 30',
    'Desk Workers': '30-Day Desk Health & Posture Habits',
    'Post-Workout Recovery': 'Habit Stacking for Post-Workout Recovery',
    'Fat Burning': '30-Day Consistency Rule for Fat Loss',
    'Hormonal Balance': 'Daily Habits for Hormonal Balance',
    'Metabolic Flexibility': 'Building Metabolic Consistency Habits',
    'Muscle Retention': '30-Day Habits for Muscle Retention',
    'Energy Boost': 'Morning Habits for All-Day High Energy',
    'Night Shift Workers': 'Night Shift Consistency & Health Habits',
    'Budget Meal Planning': 'Zero-Cost Daily Healthy Habits'
  },
  'fitness-science': {
    'Busy IT Professionals': 'What Science Says About Prolonged Sitting',
    'Vegetarians': 'Peer-Reviewed Research on Vegetarian Protein',
    'Beginners Over 30': 'Exercise Science & Muscle Aging After 30',
    'Desk Workers': 'Science of Sedentary Lifestyle Risks',
    'Post-Workout Recovery': 'Science of Muscle Recovery & DOMS',
    'Fat Burning': 'Science of Caloric Deficits & Fat Loss',
    'Hormonal Balance': 'Science of Cortisol & Hormonal Balance',
    'Metabolic Flexibility': 'Scientific Research on Metabolic Health',
    'Muscle Retention': 'Science of Muscle Protein Synthesis',
    'Energy Boost': 'Science of Sleep, Mitochondria & Energy',
    'Night Shift Workers': 'Circadian Science for Night Shift Workers',
    'Budget Meal Planning': 'Evidence-Based Fitness Hacks Demystified'
  }
};

/**
 * Returns a short, natural, editorial display title for UI rendering,
 * falling back gracefully if no explicit map entry exists.
 */
export function getEditorialDisplayTitle(catSlug: string, varItem: string, fallbackTitle: string): string {
  const catMap = EDITORIAL_DISPLAY_TITLES[catSlug];
  if (catMap && catMap[varItem]) {
    return catMap[varItem];
  }

  // Smart fallback: clean up repeated prefixes if any unmapped article is encountered
  return fallbackTitle
    .replace(/^Complete Indian Diet Guide for\s+/i, '')
    .replace(/^How to Lose Belly Fat with Indian Home Food:\s+/i, '')
    .replace(/^Hypertrophy & Muscle Building Protocol for\s+/i, '')
    .replace(/^Top High Protein Foods for\s+/i, '')
    .replace(/^High Protein Quick Recipe for\s+/i, '')
    .replace(/^Scientific Supplement Guide for\s+/i, '')
    .replace(/^Essential Women's Health Strategy for\s+/i, '');
}
